[Settings]
# Paste your Discord Webhook URL here to get status updates and screenshots
DiscordWebhook=
# Set to true to print debug messages to Discord/console
Debug=false
# If a loop lasts longer than this duration (in seconds), the macro will automatically rejoin
DefaultPatience=180
# How many losses before the macro automatically rejoins to try again (if goal is to Triumph)
Giveuptolarance=2
# below is for how much times does it checks that your tower has been placed/selected before restarting the loop (increase if you had higher ping)
IterativeReads=5
# below if you want your macro to use timescale, i dont really reccomend if you use exploding enemies modifiers or just a laggy gameplay
UseTimescale=false
# keep your tickets above this certain limit
TimescaleUntil=1
# if you dont have vip, you can use private servers to override map
PrivateServerLink=
# new ocr system, more accurate but slightly slower
UseRapidOCR=true
# error tolarance default for Findtext.ahk
PixelConfidence=0.05
ColorConfidence=0.05
# new version for level checking, set to false if you wanna use the legacy kinda broken version
UseOCR=true